module.exports = {
    apps : [
        {
          name: "HappiMobiles",
          script: "./release.js",
          watch: true,
          env: {
              "PORT": 3000,
              "NODE_ENV": "qa",
              "MONGO_DB_CONNECTION":"mongodb+srv://sowmya:iNNrxOhVfEdvsUaI@cluster0-cnw2n.mongodb.net/happi-qa",
              "ACCESS_KEY_ID":"AKIASTAEMZYQTLP6FLB4",
              "JWT_SECRET_KEY":"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",
              "BUCKET":"happimobiles",
              "SECRET_ACCESS_KEY":"happi_jwt_secret",
              "OTP_SECRET":"ETTRTFGFCFSCGJLKLLUIOYUITTFFGCFZXEAWRRTTIUIGHFER",
              "MONGO_URL":"mongodb://sowmya:iNNrxOhVfEdvsUaI@cluster0-shard-00-00-cnw2n.mongodb.net:27017,cluster0-shard-00-01-cnw2n.mongodb.net:27017,cluster0-shard-00-02-cnw2n.mongodb.net:27017/happi-qa?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin&retryWrites=true&w=majority",
              "DB_NAME":"happi-qa",
              "WARE_HOUSE":"HAPPI EXPRESS",
              "DELIVERY_CLIENT":"HAPPIEXPRESS-B2C",
              "DELIVERY_CREATE_URL":"https://staging-express.delhivery.com/api/cmu/create.json",
              "DELIVERY_TOKEN":"862117069f570afb1c1da281d47243308fe72ecb",
              "DELIVERY_GET_URL":"https://staging-express.delhivery.com/api/v1/packages/json/",
              "DELIVERY_GET_TOKEN":"862117069f570afb1c1da281d47243308fe72ecb",
              "PAYTM_MID":"Happim26189443024001",
              "PAYTM_WEBSITE":"WEBPROD",
              "PAYTM_INDUSTRY_TYPE_ID":"Retail100",
              "PAYTM_CHANNEL_ID":"WEB",
              "PAYTM_CALLBACK_URL":"https://happimobiles.com/order/paytm-return",
              "PAYTM_CHECK_SUM_KEY":"pBgjbchezWmjrORm",
              "PAYTM_ORDER_SUBMIT_URL":"https://securegw.paytm.in/order/process",
              "PAYTM_CALLBACK_LINK_URL":"https://happimobiles.com/order/paytm-return-link",
              "PINELABS_URL":"https://pinepg.in/PinePGRedirect/index",
              "PINELABS_MERCHANT_ID":"1550",
              "PINELABS_MERCHANT_ACCESS_CODE":"bdd01d1d-52ea-460b-a6a7-625a7384dbc1",
              "PINELABS_PAYMODE_ONLANDING_PAGEL":"0,1,3,4,5,10,11,12",
              "PINELABS_MERCHANT_RETURN_URL":"https://happimobiles.com/order/pinelabs-return",
              "PINELABS_NAVIGATION_MODE":"2",
              "PINELABS_TRANSACTION_TYPE":"1",
              "PINELABS_LPC_SEQ":"1",
              "PINELABS_STR_SECRET_KEY":"42F2F10AE4AE40CC858096722371EF49",
              "PINELABS_STR_HASH_TYPE":"SHA256",
              "PINELABS_UNIQUE_MERCHANT_TXNID":"ppc_UniqueMerchantTxnID",
          },
          env_production: {
              "PORT": 80,
              "NODE_ENV": "prod",
              "MONGO_DB_CONNECTION":"mongodb+srv://sowmya:iNNrxOhVfEdvsUaI@cluster0-cnw2n.mongodb.net/happi",
              "ACCESS_KEY_ID":"AKIASTAEMZYQTLP6FLB4",
              "JWT_SECRET_KEY":"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",
              "BUCKET":"happimobiles",
              "SECRET_ACCESS_KEY":"happi_jwt_secret",
              "OTP_SECRET":"ETTRTFGFCFSCGJLKLLUIOYUITTFFGCFZXEAWRRTTIUIGHFER",
              "MONGO_URL":"mongodb://sowmya:iNNrxOhVfEdvsUaI@cluster0-shard-00-00-cnw2n.mongodb.net:27017,cluster0-shard-00-01-cnw2n.mongodb.net:27017,cluster0-shard-00-02-cnw2n.mongodb.net:27017/happi?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin&retryWrites=true&w=majority",
              "DB_NAME":"happi",
              "WARE_HOUSE":"HAPPI EXPRESS",
              "DELIVERY_CLIENT":"HAPPIEXPRESS-B2C",
              "DELIVERY_CREATE_URL":"https://staging-express.delhivery.com/api/cmu/create.json",
              "DELIVERY_TOKEN":"862117069f570afb1c1da281d47243308fe72ecb",
              "DELIVERY_GET_URL":"https://staging-express.delhivery.com/api/v1/packages/json/",
              "DELIVERY_GET_TOKEN":"862117069f570afb1c1da281d47243308fe72ecb",
              "PAYTM_MID":"Happim26189443024001",
              "PAYTM_WEBSITE":"WEBPROD",
              "PAYTM_INDUSTRY_TYPE_ID":"Retail100",
              "PAYTM_CHANNEL_ID":"WEB",
              "PAYTM_CALLBACK_URL":"https://happimobiles.com/order/paytm-return",
              "PAYTM_CHECK_SUM_KEY":"pBgjbchezWmjrORm",
              "PAYTM_ORDER_SUBMIT_URL":"https://securegw.paytm.in/order/process",
              "PAYTM_CALLBACK_LINK_URL":"https://happimobiles.com/order/paytm-return-link",
              "PINELABS_URL":"https://pinepg.in/PinePGRedirect/index",
              "PINELABS_MERCHANT_ID":"1550",
              "PINELABS_MERCHANT_ACCESS_CODE":"bdd01d1d-52ea-460b-a6a7-625a7384dbc1",
              "PINELABS_PAYMODE_ONLANDING_PAGEL":"0,1,3,4,5,10,11,12",
              "PINELABS_MERCHANT_RETURN_URL":"https://happimobiles.com/order/pinelabs-return",
              "PINELABS_NAVIGATION_MODE":"2",
              "PINELABS_TRANSACTION_TYPE":"1",
              "PINELABS_LPC_SEQ":"1",
              "PINELABS_STR_SECRET_KEY":"42F2F10AE4AE40CC858096722371EF49",
              "PINELABS_STR_HASH_TYPE":"SHA256",
              "PINELABS_UNIQUE_MERCHANT_TXNID":"ppc_UniqueMerchantTxnID",
          }
        }
    ]
  }